-- =====================================================================
-- LEPAKSHI GOLD — MySQL schema (Hostinger)
-- Venkateshwara Oil Traders · e-commerce platform
--
-- Import this file once into your Hostinger database:
--   hPanel -> Databases -> phpMyAdmin -> your DB -> Import -> choose this file
-- Or from a terminal:
--   mysql -h HOST -u u750189796_lepakshi_gold -p u750189796_Lepakshi_gold < schema.sql
--
-- Engine InnoDB + utf8mb4 throughout (needed for Telugu text and ₹).
-- IDs are CHAR(36) UUIDs generated by the application layer.
-- =====================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ===================== ACCOUNTS =====================

CREATE TABLE IF NOT EXISTS users (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  email         VARCHAR(190) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  full_name     VARCHAR(120) NULL,
  phone         VARCHAR(20)  NULL,
  email_verified TINYINT(1)  NOT NULL DEFAULT 0,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Mirror of users kept for the app's profile screens.
CREATE TABLE IF NOT EXISTS profiles (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  full_name  VARCHAR(120) NULL,
  email      VARCHAR(190) NULL,
  phone      VARCHAR(20)  NULL,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_profiles_user FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_roles (
  id          CHAR(36) NOT NULL PRIMARY KEY,
  user_id     CHAR(36) NOT NULL,
  role        ENUM('owner','manager','staff') NOT NULL,
  permissions JSON     NULL,
  is_active   TINYINT(1) NOT NULL DEFAULT 1,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_role (user_id, role),
  CONSTRAINT fk_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Server-side sessions. The browser only ever holds the opaque token.
CREATE TABLE IF NOT EXISTS sessions (
  token      CHAR(64) NOT NULL PRIMARY KEY,
  user_id    CHAR(36) NOT NULL,
  user_agent VARCHAR(255) NULL,
  expires_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_sessions_user (user_id),
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===================== CATALOGUE =====================

CREATE TABLE IF NOT EXISTS categories (
  id              CHAR(36)     NOT NULL PRIMARY KEY,
  parent_id       CHAR(36)     NULL,
  name            VARCHAR(160) NOT NULL,
  name_te         VARCHAR(160) NULL,
  slug            VARCHAR(160) NOT NULL,
  description     TEXT         NULL,
  image_url       VARCHAR(500) NULL,
  banner_url      VARCHAR(500) NULL,
  sort_order      INT          NOT NULL DEFAULT 0,
  is_active       TINYINT(1)   NOT NULL DEFAULT 1,
  seo_title       VARCHAR(200) NULL,
  seo_description VARCHAR(400) NULL,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_categories_slug (slug),
  KEY idx_categories_parent (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tags (
  id   CHAR(36)     NOT NULL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(120) NOT NULL,
  UNIQUE KEY uq_tags_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attributes (
  id           CHAR(36)     NOT NULL PRIMARY KEY,
  name         VARCHAR(120) NOT NULL,
  slug         VARCHAR(120) NOT NULL,
  display_type ENUM('pills','dropdown','swatch') NOT NULL DEFAULT 'pills',
  sort_order   INT          NOT NULL DEFAULT 0,
  UNIQUE KEY uq_attributes_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS attribute_terms (
  id           CHAR(36)     NOT NULL PRIMARY KEY,
  attribute_id CHAR(36)     NOT NULL,
  name         VARCHAR(120) NOT NULL,
  slug         VARCHAR(120) NOT NULL,
  sort_order   INT          NOT NULL DEFAULT 0,
  UNIQUE KEY uq_term (attribute_id, slug),
  CONSTRAINT fk_terms_attribute FOREIGN KEY (attribute_id) REFERENCES attributes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
  id                CHAR(36)     NOT NULL PRIMARY KEY,
  name              VARCHAR(200) NOT NULL,
  name_te           VARCHAR(200) NULL,
  slug              VARCHAR(200) NOT NULL,
  sku_base          VARCHAR(60)  NULL,
  type              ENUM('simple','variable') NOT NULL DEFAULT 'variable',
  category_id       CHAR(36)     NULL,
  short_description VARCHAR(500) NULL,
  description       MEDIUMTEXT   NULL,
  thumbnail_url     VARCHAR(500) NULL,
  gallery           JSON         NULL,
  gst_rate          DECIMAL(5,2) NOT NULL DEFAULT 5.00,
  hsn_code          VARCHAR(20)  NULL,
  is_organic         TINYINT(1)   NOT NULL DEFAULT 1,
  extraction        VARCHAR(120) NULL,
  shelf_life        VARCHAR(120) NULL,
  ingredients       VARCHAR(500) NULL,
  storage           VARCHAR(500) NULL,
  status            ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
  is_featured       TINYINT(1)   NOT NULL DEFAULT 0,
  sort_order        INT          NOT NULL DEFAULT 0,
  seo_title         VARCHAR(200) NULL,
  seo_description   VARCHAR(400) NULL,
  upsell_ids        JSON         NULL,
  crosssell_ids     JSON         NULL,
  created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_products_slug (slug),
  KEY idx_products_category (category_id),
  KEY idx_products_status (status),
  KEY idx_products_featured (is_featured),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_tags (
  product_id CHAR(36) NOT NULL,
  tag_id     CHAR(36) NOT NULL,
  PRIMARY KEY (product_id, tag_id),
  CONSTRAINT fk_pt_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_pt_tag     FOREIGN KEY (tag_id)     REFERENCES tags(id)     ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_attributes (
  product_id          CHAR(36)  NOT NULL,
  attribute_id        CHAR(36)  NOT NULL,
  used_for_variations TINYINT(1) NOT NULL DEFAULT 1,
  sort_order          INT       NOT NULL DEFAULT 0,
  PRIMARY KEY (product_id, attribute_id),
  CONSTRAINT fk_pa_product   FOREIGN KEY (product_id)   REFERENCES products(id)   ON DELETE CASCADE,
  CONSTRAINT fk_pa_attribute FOREIGN KEY (attribute_id) REFERENCES attributes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_attribute_terms (
  product_id   CHAR(36) NOT NULL,
  attribute_id CHAR(36) NOT NULL,
  term_id      CHAR(36) NOT NULL,
  PRIMARY KEY (product_id, term_id),
  CONSTRAINT fk_pat_product FOREIGN KEY (product_id) REFERENCES products(id)        ON DELETE CASCADE,
  CONSTRAINT fk_pat_term    FOREIGN KEY (term_id)    REFERENCES attribute_terms(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Stock lives HERE, on the variation, never on the product.
CREATE TABLE IF NOT EXISTS variations (
  id                  CHAR(36)      NOT NULL PRIMARY KEY,
  product_id          CHAR(36)      NOT NULL,
  sku                 VARCHAR(80)   NOT NULL,
  barcode             VARCHAR(40)   NULL,
  label               VARCHAR(80)   NULL,
  option_map          JSON          NULL,
  price               DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  sale_price          DECIMAL(10,2) NULL,
  sale_starts_at      DATETIME      NULL,
  sale_ends_at        DATETIME      NULL,
  cost_price          DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  weight_grams        INT           NOT NULL DEFAULT 0,
  length_cm           DECIMAL(6,2)  NULL,
  width_cm            DECIMAL(6,2)  NULL,
  height_cm           DECIMAL(6,2)  NULL,
  manage_stock        TINYINT(1)    NOT NULL DEFAULT 1,
  stock_quantity      DECIMAL(12,3) NOT NULL DEFAULT 0,
  low_stock_threshold DECIMAL(12,3) NOT NULL DEFAULT 5,
  backorders          ENUM('no','notify','allow') NOT NULL DEFAULT 'no',
  image_url           VARCHAR(500)  NULL,
  is_active           TINYINT(1)    NOT NULL DEFAULT 1,
  sort_order          INT           NOT NULL DEFAULT 0,
  created_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_variations_sku (sku),
  UNIQUE KEY uq_variations_barcode (barcode),
  KEY idx_variations_product (product_id),
  CONSTRAINT fk_variations_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Every stock change writes one row here. Never UPDATE stock_quantity directly.
CREATE TABLE IF NOT EXISTS inventory_movements (
  id             CHAR(36)      NOT NULL PRIMARY KEY,
  variation_id   CHAR(36)      NOT NULL,
  type           ENUM('purchase','production','sale','return','damage','adjustment','cancellation') NOT NULL,
  quantity       DECIMAL(12,3) NOT NULL,
  balance_after  DECIMAL(12,3) NOT NULL,
  reference_type VARCHAR(40)   NULL,
  reference_id   CHAR(36)      NULL,
  note           VARCHAR(500)  NULL,
  created_by     CHAR(36)      NULL,
  created_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_movements_variation (variation_id, created_at),
  CONSTRAINT fk_movements_variation FOREIGN KEY (variation_id) REFERENCES variations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===================== CUSTOMER DATA =====================

CREATE TABLE IF NOT EXISTS addresses (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  customer_id CHAR(36)     NOT NULL,
  type        ENUM('shipping','billing') NOT NULL DEFAULT 'shipping',
  label       VARCHAR(60)  NULL,
  full_name   VARCHAR(120) NULL,
  phone       VARCHAR(20)  NULL,
  line1       VARCHAR(200) NULL,
  line2       VARCHAR(200) NULL,
  landmark    VARCHAR(160) NULL,
  city        VARCHAR(120) NULL,
  district    VARCHAR(120) NULL,
  state       VARCHAR(120) NULL DEFAULT 'Andhra Pradesh',
  pincode     VARCHAR(10)  NULL,
  is_default  TINYINT(1)   NOT NULL DEFAULT 0,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_addresses_customer (customer_id),
  CONSTRAINT fk_addresses_user FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS wishlists (
  id          CHAR(36) NOT NULL PRIMARY KEY,
  customer_id CHAR(36) NOT NULL,
  product_id  CHAR(36) NOT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_wishlist (customer_id, product_id),
  CONSTRAINT fk_wishlist_user    FOREIGN KEY (customer_id) REFERENCES users(id)    ON DELETE CASCADE,
  CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id)  REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===================== ORDERS =====================

CREATE TABLE IF NOT EXISTS orders (
  id              CHAR(36)      NOT NULL PRIMARY KEY,
  order_no        VARCHAR(40)   NOT NULL,
  customer_id     CHAR(36)      NULL,
  is_guest        TINYINT(1)    NOT NULL DEFAULT 1,
  contact_name    VARCHAR(120)  NULL,
  contact_phone   VARCHAR(20)   NULL,
  contact_email   VARCHAR(190)  NULL,
  shipping_address JSON         NULL,
  billing_address  JSON         NULL,
  items_subtotal  DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  discount_total  DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  coupon_code     VARCHAR(40)   NULL,
  shipping_total  DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  tax_total       DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  grand_total     DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  payment_method  ENUM('cod','razorpay','upi','bank_transfer') NOT NULL DEFAULT 'cod',
  payment_status  ENUM('pending','paid','failed','refunded','partially_refunded') NOT NULL DEFAULT 'pending',
  payment_ref     VARCHAR(120)  NULL,
  status          ENUM('pending','processing','packed','shipped','out_for_delivery','delivered','cancelled','refunded','failed','on_hold') NOT NULL DEFAULT 'pending',
  courier_name    VARCHAR(120)  NULL,
  tracking_number VARCHAR(120)  NULL,
  tracking_url    VARCHAR(500)  NULL,
  customer_note   VARCHAR(600)  NULL,
  placed_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_orders_no (order_no),
  KEY idx_orders_customer (customer_id),
  KEY idx_orders_status (status),
  KEY idx_orders_placed (placed_at),
  KEY idx_orders_phone (contact_phone)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_items (
  id                       CHAR(36)      NOT NULL PRIMARY KEY,
  order_id                 CHAR(36)      NOT NULL,
  product_id               CHAR(36)      NULL,
  variation_id             CHAR(36)      NULL,
  product_name_snapshot    VARCHAR(200)  NULL,
  variation_label_snapshot VARCHAR(80)   NULL,
  sku_snapshot             VARCHAR(80)   NULL,
  image_snapshot           VARCHAR(500)  NULL,
  quantity                 DECIMAL(10,2) NOT NULL DEFAULT 1,
  unit_price               DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  cost_price_snapshot      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  gst_rate                 DECIMAL(5,2)  NOT NULL DEFAULT 0.00,
  line_total               DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  KEY idx_items_order (order_id),
  CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_notes (
  id                  CHAR(36)     NOT NULL PRIMARY KEY,
  order_id            CHAR(36)     NOT NULL,
  note                VARCHAR(1000) NOT NULL,
  is_customer_visible TINYINT(1)   NOT NULL DEFAULT 0,
  created_by          CHAR(36)     NULL,
  created_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_notes_order (order_id),
  CONSTRAINT fk_notes_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_status_history (
  id          CHAR(36) NOT NULL PRIMARY KEY,
  order_id    CHAR(36) NOT NULL,
  from_status VARCHAR(40) NULL,
  to_status   VARCHAR(40) NOT NULL,
  changed_by  CHAR(36) NULL,
  changed_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_history_order (order_id),
  CONSTRAINT fk_history_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS refunds (
  id          CHAR(36)      NOT NULL PRIMARY KEY,
  order_id    CHAR(36)      NOT NULL,
  amount      DECIMAL(12,2) NOT NULL,
  reason      VARCHAR(300)  NULL,
  restock     TINYINT(1)    NOT NULL DEFAULT 0,
  refunded_by CHAR(36)      NULL,
  created_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_refunds_order (order_id),
  CONSTRAINT fk_refunds_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===================== MARKETING =====================

CREATE TABLE IF NOT EXISTS coupons (
  id                       CHAR(36)      NOT NULL PRIMARY KEY,
  code                     VARCHAR(40)   NOT NULL,
  description              VARCHAR(300)  NULL,
  type                     ENUM('percent','fixed_cart','fixed_product','free_shipping') NOT NULL DEFAULT 'percent',
  value                    DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  min_spend                DECIMAL(10,2) NULL,
  max_discount             DECIMAL(10,2) NULL,
  usage_limit              INT           NULL,
  usage_limit_per_customer INT           NULL,
  used_count               INT           NOT NULL DEFAULT 0,
  applies_to               ENUM('all','products','categories') NOT NULL DEFAULT 'all',
  product_ids              JSON          NULL,
  category_ids             JSON          NULL,
  excluded_ids             JSON          NULL,
  first_order_only         TINYINT(1)    NOT NULL DEFAULT 0,
  starts_at                DATETIME      NULL,
  expires_at               DATETIME      NULL,
  is_active                TINYINT(1)    NOT NULL DEFAULT 1,
  created_at               DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_coupons_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS coupon_usages (
  id          CHAR(36)      NOT NULL PRIMARY KEY,
  coupon_id   CHAR(36)      NOT NULL,
  order_id    CHAR(36)      NULL,
  customer_id CHAR(36)      NULL,
  amount      DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  used_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_usage_coupon (coupon_id),
  CONSTRAINT fk_usage_coupon FOREIGN KEY (coupon_id) REFERENCES coupons(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===================== SHIPPING & TAX =====================

CREATE TABLE IF NOT EXISTS shipping_zones (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  name       VARCHAR(120) NOT NULL,
  match_type ENUM('pincode','district','state','rest') NOT NULL DEFAULT 'rest',
  `values`   JSON         NULL,
  sort_order INT          NOT NULL DEFAULT 0,
  is_active  TINYINT(1)   NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS shipping_methods (
  id          CHAR(36)      NOT NULL PRIMARY KEY,
  zone_id     CHAR(36)      NOT NULL,
  name        VARCHAR(120)  NOT NULL,
  type        ENUM('flat','free_above','weight_based','pickup') NOT NULL DEFAULT 'flat',
  cost        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  free_above  DECIMAL(10,2) NULL,
  per_kg_rate DECIMAL(10,2) NULL,
  min_days    INT           NULL,
  max_days    INT           NULL,
  is_active   TINYINT(1)    NOT NULL DEFAULT 1,
  KEY idx_methods_zone (zone_id),
  CONSTRAINT fk_methods_zone FOREIGN KEY (zone_id) REFERENCES shipping_zones(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pincode_serviceability (
  id             CHAR(36)     NOT NULL PRIMARY KEY,
  pincode        VARCHAR(10)  NOT NULL,
  city           VARCHAR(120) NULL,
  district       VARCHAR(120) NULL,
  state          VARCHAR(120) NULL,
  is_serviceable TINYINT(1)   NOT NULL DEFAULT 1,
  cod_available  TINYINT(1)   NOT NULL DEFAULT 1,
  eta_days       INT          NOT NULL DEFAULT 4,
  UNIQUE KEY uq_pincode (pincode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===================== CONTENT =====================

CREATE TABLE IF NOT EXISTS pages (
  id              CHAR(36)     NOT NULL PRIMARY KEY,
  slug            VARCHAR(120) NOT NULL,
  title           VARCHAR(200) NOT NULL,
  content         JSON         NULL,
  seo_title       VARCHAR(200) NULL,
  seo_description VARCHAR(400) NULL,
  is_published    TINYINT(1)   NOT NULL DEFAULT 1,
  updated_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_pages_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS content_blocks (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  `key`      VARCHAR(80)  NOT NULL,
  data       JSON         NULL,
  is_active  TINYINT(1)   NOT NULL DEFAULT 1,
  sort_order INT          NOT NULL DEFAULT 0,
  UNIQUE KEY uq_block_key (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS banners (
  id               CHAR(36)     NOT NULL PRIMARY KEY,
  title            VARCHAR(200) NULL,
  subtitle         VARCHAR(300) NULL,
  image_url        VARCHAR(500) NULL,
  mobile_image_url VARCHAR(500) NULL,
  link_url         VARCHAR(500) NULL,
  placement        VARCHAR(60)  NULL,
  sort_order       INT          NOT NULL DEFAULT 0,
  starts_at        DATETIME     NULL,
  ends_at          DATETIME     NULL,
  is_active        TINYINT(1)   NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reviews (
  id                   CHAR(36)     NOT NULL PRIMARY KEY,
  product_id           CHAR(36)     NOT NULL,
  customer_id          CHAR(36)     NULL,
  order_id             CHAR(36)     NULL,
  rating               TINYINT      NOT NULL,
  title                VARCHAR(200) NULL,
  body                 TEXT         NULL,
  images               JSON         NULL,
  author_name          VARCHAR(120) NULL,
  author_town          VARCHAR(120) NULL,
  is_verified_purchase TINYINT(1)   NOT NULL DEFAULT 0,
  reply                TEXT         NULL,
  status               ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_reviews_product (product_id, status),
  CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS faqs (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  question   VARCHAR(400) NOT NULL,
  answer     TEXT         NOT NULL,
  category   VARCHAR(80)  NULL,
  sort_order INT          NOT NULL DEFAULT 0,
  is_active  TINYINT(1)   NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS enquiries (
  id         CHAR(36)     NOT NULL PRIMARY KEY,
  name       VARCHAR(120) NOT NULL,
  phone      VARCHAR(20)  NULL,
  email      VARCHAR(190) NULL,
  type       VARCHAR(60)  NULL,
  message    TEXT         NULL,
  created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===================== OPS =====================

CREATE TABLE IF NOT EXISTS media (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  url         VARCHAR(500) NOT NULL,
  filename    VARCHAR(255) NULL,
  alt_text    VARCHAR(300) NULL,
  folder      VARCHAR(80)  NULL,
  size_bytes  INT          NULL,
  uploaded_by CHAR(36)     NULL,
  created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications_log (
  id        CHAR(36)     NOT NULL PRIMARY KEY,
  channel   ENUM('email','whatsapp','sms') NOT NULL,
  template  VARCHAR(80)  NULL,
  recipient VARCHAR(190) NULL,
  order_id  CHAR(36)     NULL,
  status    VARCHAR(40)  NULL,
  error     VARCHAR(500) NULL,
  sent_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Single-row store configuration. id is always 1.
CREATE TABLE IF NOT EXISTS settings (
  id                     TINYINT(1)    NOT NULL PRIMARY KEY DEFAULT 1,
  store_name             VARCHAR(120)  NULL,
  legal_name             VARCHAR(160)  NULL,
  address                VARCHAR(500)  NULL,
  phone                  VARCHAR(20)   NULL,
  whatsapp               VARCHAR(20)   NULL,
  email                  VARCHAR(190)  NULL,
  gstin                  VARCHAR(20)   NULL,
  fssai_no               VARCHAR(30)   NULL,
  logo_url               VARCHAR(500)  NULL,
  favicon_url            VARCHAR(500)  NULL,
  order_prefix           VARCHAR(10)   NULL DEFAULT 'LG',
  next_order_number      INT           NULL DEFAULT 1001,
  currency               VARCHAR(10)   NULL DEFAULT 'INR',
  prices_include_tax     TINYINT(1)    NULL DEFAULT 1,
  free_shipping_above    DECIMAL(10,2) NULL DEFAULT 999.00,
  default_shipping_fee   DECIMAL(10,2) NULL DEFAULT 60.00,
  cod_enabled            TINYINT(1)    NULL DEFAULT 1,
  cod_extra_fee          DECIMAL(10,2) NULL DEFAULT 0.00,
  razorpay_enabled       TINYINT(1)    NULL DEFAULT 0,
  low_stock_alert_email  VARCHAR(190)  NULL,
  order_email_recipients JSON          NULL,
  social_links           JSON          NULL,
  seo_defaults           JSON          NULL,
  maintenance_mode       TINYINT(1)    NULL DEFAULT 0,
  updated_at             DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
