/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as AuthenticatedAccountRouteRouteImport } from './routes/_authenticated/account/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as OrderOrderNoRouteImport } from './routes/order.$orderNo'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopCategorySlugRouteImport } from './routes/shop.$categorySlug'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedAccountAddressesRouteImport } from './routes/_authenticated/account/addresses'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account/orders'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account/profile'
import { Route as AuthenticatedAccountReviewsRouteImport } from './routes/_authenticated/account/reviews'
import { Route as AuthenticatedAccountWishlistRouteImport } from './routes/_authenticated/account/wishlist'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAttributesRouteImport } from './routes/_authenticated/admin/attributes'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin/categories'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin/orders'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin/reports'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminShippingRouteImport } from './routes/_authenticated/admin/shipping'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin/stock'
import { Route as AuthenticatedAdminTaxRouteImport } from './routes/_authenticated/admin/tax'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRouteRoute =
  AuthenticatedAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrderOrderNoRoute = OrderOrderNoRouteImport.update({
  id: '/order/$orderNo',
  path: '/order/$orderNo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategorySlugRoute = ShopCategorySlugRouteImport.update({
  id: '/shop/$categorySlug',
  path: '/shop/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountAddressesRoute =
  AuthenticatedAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountReviewsRoute =
  AuthenticatedAccountReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountWishlistRoute =
  AuthenticatedAccountWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAttributesRoute =
  AuthenticatedAdminAttributesRouteImport.update({
    id: '/attributes',
    path: '/attributes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminShippingRoute =
  AuthenticatedAdminShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTaxRoute = AuthenticatedAdminTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/order/$orderNo': typeof OrderOrderNoRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$categorySlug': typeof ShopCategorySlugRoute
  '/shop/': typeof ShopIndexRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/reviews': typeof AuthenticatedAccountReviewsRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/admin/attributes': typeof AuthenticatedAdminAttributesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/tax': typeof AuthenticatedAdminTaxRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/order/$orderNo': typeof OrderOrderNoRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$categorySlug': typeof ShopCategorySlugRoute
  '/shop': typeof ShopIndexRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/account/reviews': typeof AuthenticatedAccountReviewsRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/admin/attributes': typeof AuthenticatedAdminAttributesRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/tax': typeof AuthenticatedAdminTaxRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/order/$orderNo': typeof OrderOrderNoRoute
  '/product/$slug': typeof ProductSlugRoute
  '/shop/$categorySlug': typeof ShopCategorySlugRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/account/reviews': typeof AuthenticatedAccountReviewsRoute
  '/_authenticated/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/_authenticated/admin/attributes': typeof AuthenticatedAdminAttributesRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/tax': typeof AuthenticatedAdminTaxRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/returns'
    | '/shipping-policy'
    | '/terms'
    | '/track-order'
    | '/account'
    | '/admin'
    | '/order/$orderNo'
    | '/product/$slug'
    | '/shop/$categorySlug'
    | '/shop/'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/reviews'
    | '/account/wishlist'
    | '/admin/attributes'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/stock'
    | '/admin/tax'
    | '/account/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/returns'
    | '/shipping-policy'
    | '/terms'
    | '/track-order'
    | '/order/$orderNo'
    | '/product/$slug'
    | '/shop/$categorySlug'
    | '/shop'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/reviews'
    | '/account/wishlist'
    | '/admin/attributes'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/media'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/stock'
    | '/admin/tax'
    | '/account'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/returns'
    | '/shipping-policy'
    | '/terms'
    | '/track-order'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/order/$orderNo'
    | '/product/$slug'
    | '/shop/$categorySlug'
    | '/shop/'
    | '/_authenticated/account/addresses'
    | '/_authenticated/account/orders'
    | '/_authenticated/account/profile'
    | '/_authenticated/account/reviews'
    | '/_authenticated/account/wishlist'
    | '/_authenticated/admin/attributes'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/shipping'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/tax'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  OrderOrderNoRoute: typeof OrderOrderNoRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShopCategorySlugRoute: typeof ShopCategorySlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/order/$orderNo': {
      id: '/order/$orderNo'
      path: '/order/$orderNo'
      fullPath: '/order/$orderNo'
      preLoaderRoute: typeof OrderOrderNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$categorySlug': {
      id: '/shop/$categorySlug'
      path: '/shop/$categorySlug'
      fullPath: '/shop/$categorySlug'
      preLoaderRoute: typeof ShopCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/addresses': {
      id: '/_authenticated/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AuthenticatedAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/reviews': {
      id: '/_authenticated/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AuthenticatedAccountReviewsRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/wishlist': {
      id: '/_authenticated/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AuthenticatedAccountWishlistRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/attributes': {
      id: '/_authenticated/admin/attributes'
      path: '/attributes'
      fullPath: '/admin/attributes'
      preLoaderRoute: typeof AuthenticatedAdminAttributesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/shipping': {
      id: '/_authenticated/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AuthenticatedAdminShippingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tax': {
      id: '/_authenticated/admin/tax'
      path: '/tax'
      fullPath: '/admin/tax'
      preLoaderRoute: typeof AuthenticatedAdminTaxRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAccountRouteRouteChildren {
  AuthenticatedAccountAddressesRoute: typeof AuthenticatedAccountAddressesRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountReviewsRoute: typeof AuthenticatedAccountReviewsRoute
  AuthenticatedAccountWishlistRoute: typeof AuthenticatedAccountWishlistRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteRouteChildren: AuthenticatedAccountRouteRouteChildren =
  {
    AuthenticatedAccountAddressesRoute: AuthenticatedAccountAddressesRoute,
    AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
    AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
    AuthenticatedAccountReviewsRoute: AuthenticatedAccountReviewsRoute,
    AuthenticatedAccountWishlistRoute: AuthenticatedAccountWishlistRoute,
    AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  }

const AuthenticatedAccountRouteRouteWithChildren =
  AuthenticatedAccountRouteRoute._addFileChildren(
    AuthenticatedAccountRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAttributesRoute: typeof AuthenticatedAdminAttributesRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminShippingRoute: typeof AuthenticatedAdminShippingRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminTaxRoute: typeof AuthenticatedAdminTaxRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAttributesRoute: AuthenticatedAdminAttributesRoute,
    AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
    AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
    AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
    AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
    AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminShippingRoute: AuthenticatedAdminShippingRoute,
    AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
    AuthenticatedAdminTaxRoute: AuthenticatedAdminTaxRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRouteRoute: typeof AuthenticatedAccountRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRouteRoute: AuthenticatedAccountRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  OrderOrderNoRoute: OrderOrderNoRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShopCategorySlugRoute: ShopCategorySlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
